# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: SonarCloud
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'project2bois'
    scannerMode: 'MSBuild'
    projectKey: 'project2.123'
    projectName: 'Project2'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './SocialMediaApp/WebApp'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './SocialMediaApp/Testing'
    
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result